### ISSUE TITLE
国库资金销毁相关信息建议暂时去掉

### ISSUE THREAD

**Issue by feilun-feilun** [chainx-org/chainx-testnet-bug-bounty#10]
**Describe the bug**
按目前显示，议会资金在2.0版被列为国库资金，由议员投票进行支出管理，一次销毁数额巨大，波卡有销毁机制，但PCX总量恒定，与DOT通胀不同，所以建议2.0版本暂时不引入国库资金销毁的机制，未来如果需要，再由社区投票决定是否引入该机制。

**Screenshots**
![屏幕快照 2020-11-06 上午12 42 23](https://user-images.githubusercontent.com/49551621/98270367-c5a8e580-1fc9-11eb-8365-b103bd4cf893.png)

**Account Info**
Node: Feilun
ChainX Wallet Address(Major Chain):
5U2Cty9khm9aW762o14GUHHBcLU1PbqRuRomW33EbQpUAHxS

**Comment by liuchengxu** [comment]
2.0-beta 测试网上链上目前没有销毁，不过销毁参数没有同步设置，https://github.com/chainx-org/ChainX/pull/332 会进行修复。

链上升级后，这里会显示销毁为0。也可以直接去掉，看后期设计 @qinghuan-chain .
