### ISSUE TITLE
测试网启链遗留问题

### ISSUE THREAD

**Issue by stw-github** [chainx-org/chainx-testnet-bug-bounty#11]
**Describe the bug**
测试网启动后官方设置了一批验证人进行内测，内测通过后于区块高度3000多块时将内测的验证人全部退选，并对社区宣布公测网络开放，由于内测验证人大批退出导致grandpa确认数低于要求的比例，导致整链的finalized区块卡住无法前进。

**To Reproduce**
查看日志文件，可以观察到finalized区块停留在3348高度。

**Expected behavior**
finalized 高度应该在离最新块高不远的地方。

**Log**
Nov 06 07:24:30.535  INFO ✨ Imported #11697 (0x4e56…3af4)    
Nov 06 07:24:34.653  INFO  Idle (13 peers), best: #11697 (0x4e56…3af4), finalized #3348 (0x6820…c726), ⬇ 9.0kiB/s ⬆ 3.2kiB/s    
Nov 06 07:24:36.513  INFO ✨ Imported #11698 (0x1548…7aa5)    
Nov 06 07:24:39.653  INFO  Idle (13 peers), best: #11698 (0x1548…7aa5), finalized #3348 (0x6820…c726), ⬇ 5.8kiB/s ⬆ 3.4kiB/s    
Nov 06 07:24:42.462  INFO ✨ Imported #11699 (0xc8b1…87fa)    
Nov 06 07:24:44.653  INFO  Idle (13 peers), best: #11699 (0xc8b1…87fa), finalized #3348 (0x6820…c726), ⬇ 11.1kiB/s ⬆ 4.1kiB/s    
Nov 06 07:24:48.100  INFO ✨ Imported #11700 (0x276f…e450)    
Nov 06 07:24:49.653  INFO  Idle (13 peers), best: #11700 (0x276f…e450), finalized #3348 (0x6820…c726), ⬇ 11.3kiB/s ⬆ 3.6kiB/s   

**Account Info**
UserOrNode: stw
ChainX Wallet Address(Major Chain): 5SWAPQw1XgFWvfgwZvLc4MHNiZQMJsrkNxgMcb3pxgRQmnbW

**Comment by liuchengxu** [comment]
Genesis时已经导入了 1.0 的所有状态，包括大部分活跃验证人，但是默认退选，只有几个2.0的创世节点会参选，参与网络早起共识。启动详情会在迁移文档中说明 https://github.com/chainx-org/documentation/pull/7。

Finalized 的问题正在查。
