### ISSUE TITLE
给已退选的节点投票成功

### ISSUE THREAD

**Issue by stw-github** [chainx-org/chainx-testnet-bug-bounty#18]
**Describe the bug**
可以给已退选的节点投票，且投票成功。这个设计不太合理。

**To Reproduce**
质押页面随便给一个已退选节点投票

**Expected behavior**
已退选节点，意味着其不再担任节点角色，可能只是想做普通的提名人，此时别的提名人给他投票应该不能成功。

**Log**
https://scan-v2.chainx.org/extrinsics/0x32fd191cff61090cbb6d3692835d8a59a218aedf2f608f236ed7cbacb2f9e12a

**Account Info**
UserOrNode: stw
ChainX Wallet Address(Major Chain): 5SWAPQw1XgFWvfgwZvLc4MHNiZQMJsrkNxgMcb3pxgRQmnbW

**Comment by liuchengxu** [comment]
给已退选的节点投票不再有收益，不影响共识，这是用户自己的选择，链上不做干预。
