### ISSUE TITLE
Balance not showing

### ISSUE THREAD

**Issue by cLEarnProject** [chainx-org/chainx-testnet-bug-bounty#19]
**Describe the bug**
Balance of xBTC is showing sometimes N/A for wallet created via website and for wallet created via infura it shows always 0 xBTC . 

**To Reproduce**
Created 2 accounts , one with infura,  one via website.

**Expected behavior**
To see 0 always on wallet created via website

**Log**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/53353843/98465503-18ed8480-21d2-11eb-936b-b1f9f7eff990.png)

**Account Info**
UserOrNode: User 
ChainX Wallet Address(Main Chain): 5SsD8toyF9tiPcqbYf4pSbFB2VXZh7fKT64ciPBK5xnEGFfi

**Comment by aaurix** [comment]
fixed

**Comment by cLEarnProject** [comment]
thanks
