### ISSUE TITLE
Redeem didn't return PCX

### ISSUE THREAD

**Issue by Exxibition** [chainx-org/chainx-testnet-bug-bounty#22]
**Describe the bug**
Redeeming the Unbonded worked, but didn't show up on the accounts balance. The 'Redeem ID' was left empty as it has no description of what this is supposed to be.

**To Reproduce**
Unbound staked PCX from a node and after three days, redeem this PCX without entering a Redeem ID

**Expected behavior**
Redeemed PCX to be returned to the wallet and become transferable

**Log**
extrinsic hash: 0x28787a82e7b7b78a18af63d3f64f442fa20be7a540a85a9692f0e4313496e5c0

**Screenshots**

**Account Info**
UserOrNode: User
ChainX Wallet Address(Main Chain): 5TLM4wEBMEJysMSj5TY5BKv3K4aaE1XRE5mv6FUt6NzT1PFT

**Comment by aaurix** [comment]
fixed
