### ISSUE TITLE
DEX挂单异常，且提交交易后无记录

### ISSUE THREAD

**Issue by feilun-feilun** [chainx-org/chainx-testnet-bug-bounty#24]
**Describe the bug**
1、DEX挂单可以输入的数值异常，余额充足，但无法输入高数值，详见图1；
2、上述的小额挂单，提交交易后，DEX内不显示。

**Screenshots**
![屏幕快照 2020-11-14 上午11 16 19](https://user-images.githubusercontent.com/49551621/99138448-833b7480-266b-11eb-9efc-dfa0dbdefe6a.png)
![屏幕快照 2020-11-14 上午11 21 39](https://user-images.githubusercontent.com/49551621/99138484-d3b2d200-266b-11eb-8012-f0429d82026b.png)
挂单提交成功，但dex并无相应的订单显示出；

**Account Info**
Node: FEILUN
ChainX Wallet Address(Main Chain): 5U2Cty9khm9aW762o14GUHHBcLU1PbqRuRomW33EbQpUAHxS

**Comment by aaurix** [comment]
fixed
