### ISSUE TITLE
浏览器不显示近期交易记录

### ISSUE THREAD

**Issue by feilun-feilun** [chainx-org/chainx-testnet-bug-bounty#25]
**Describe the bug**
最新交易记录，在浏览器上均为显示；
地址1：5ELoq1HBSEALJ1r14Qo1nSHjFMzkiaFkVkoiRvjrpHHFDJCL
地址2：5GPCXijT6DS3rDireRHkQAkjm87JwJraQQ6GQtreH5n3sJxt
两个地址于11月14日11：00之后均有提息、抵押、转账等操作，但浏览器均查询不到。

**Screenshots**
![屏幕快照 2020-11-14 上午11 48 16](https://user-images.githubusercontent.com/49551621/99138951-9b14f780-266f-11eb-9a3e-6f5e7e9d2054.png)

Account Info
Node: FEILUN
ChainX Wallet Address(Main Chain): 5U2Cty9khm9aW762o14GUHHBcLU1PbqRuRomW33EbQpUAHxS

**Comment by tarvos21** [comment]
Hi, @feilun-feilun ,I have checked in the browser, there are records for the addresses now. How about it now?
