### ISSUE TITLE
DEX交易数据，浏览器与钱包显示不一致

### ISSUE THREAD

**Issue by feilun-feilun** [chainx-org/chainx-testnet-bug-bounty#26]
**Describe the bug**
在钱包提交的订单，钱包中显示成交，且相应余额发生了变化，而浏览器的当前委托列表却显示成交率均为0%；
同时在历史委托列表中，也有相同的订单列表展示；
且每次成交，挂单列表的总额都会增加
钱包地址：5GPCXijT6DS3rDireRHkQAkjm87JwJraQQ6GQtreH5n3sJxt

ps. 经过观察，目前版本DEX，pcx卖单可卖数量与XBTC余额一致，原因未知；

**Screenshots**
![屏幕快照 2020-11-16 上午11 26 36](https://user-images.githubusercontent.com/49551621/99210242-4c4a9780-2800-11eb-87b5-e9551427cdc8.png)
![屏幕快照 2020-11-16 上午11 26 58](https://user-images.githubusercontent.com/49551621/99210250-4f458800-2800-11eb-8c40-7932536c9b4e.png)

Account Info
Node: FEILUN
ChainX Wallet Address(Main Chain): 5U2Cty9khm9aW762o14GUHHBcLU1PbqRuRomW33EbQpUAHxS

**Comment by aaurix** [comment]
fixed
