### ISSUE TITLE
赎回失败

### ISSUE THREAD

**Issue by AeReach** [chainx-org/chainx-testnet-bug-bounty#29]
**Describe the bug**
赎回投票时没有成功。

**To Reproduce**
1、给验证人投票后进入‘我的质押’页面；
2、提息能够成功；
3、提息完成后点赎回，交易签名并广播后收到如下错误通知：
![image](https://user-images.githubusercontent.com/12623739/99219457-a4d95f00-2817-11eb-97cf-4840de8b245e.png)

**Expected behavior**
期望结果为能够赎回成功。

**Log**
![image](https://user-images.githubusercontent.com/12623739/99219457-a4d95f00-2817-11eb-97cf-4840de8b245e.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/12623739/99219457-a4d95f00-2817-11eb-97cf-4840de8b245e.png)

**Account Info**
UserOrNode: User. 
ChainX Wallet Address(Main Chain): 5EFYygRLe4kG3LCJuM3pVhAZPAcSCKudoTbeUXtWX5fsX7AP。

**Comment by liuchengxu** [comment]
用户没有可赎回，点击赎回报错符合预期。
