### ISSUE TITLE
BTC 跨链充值未到账 

### ISSUE THREAD

**Issue by feilun-feilun** [chainx-org/chainx-testnet-bug-bounty#3]
**Describe the bug**
1、BTC跨链充值未到账，充值哈希：
5U2Cty9khm9aW762o14GUHHBcLU1PbqRuRomW33EbQpUAHxS
此消息发布时，已经满6个确认；
充值地址：mzRxaHfQqYEPb6bCwWwtYiKfPsLresACUn
充值数量：0.018
chainx 2.0 区块浏览器无法查到相关充值交易。

**Account Info**
Node: Feilun
ChainX Wallet Address(Major Chain): 
5U2Cty9khm9aW762o14GUHHBcLU1PbqRuRomW33EbQpUAHxS

**Comment by koushiro** [comment]
relay识别账户地址的bug, 今天内会修复，之前未到帐的BTC会之后手动发送交易上链

**Comment by koushiro** [comment]
BTC已经到账 https://scan-v2.chainx.org/accounts/5ELoq1HBSEALJ1r14Qo1nSHjFMzkiaFkVkoiRvjrpHHFDJCL
