### ISSUE TITLE
mainnet-pre阶段钱包自动重置

### ISSUE THREAD

**Issue by stw-github** [chainx-org/chainx-testnet-bug-bounty#34]
**Describe the bug**
通过json恢复的钱包，在页面刷新后消失

**To Reproduce**
在该页面https://dapp-v2.chainx.org/?rpc=wss%3A%2F%2Ftestnet-1.chainx.org%2Fws#/accounts通过恢复json的方式导入钱包，刷新页面后，导入的钱包消失。

**Account Info**
UserOrNode: stw
ChainX Wallet Address(Major Chain): 5SWAPQw1XgFWvfgwZvLc4MHNiZQMJsrkNxgMcb3pxgRQmnbW

**Comment by aaurix** [comment]
没有复现，是正常的
