### ISSUE TITLE
mainnet-pre阶段注册节点异常

### ISSUE THREAD

**Issue by TideDuo** [chainx-org/chainx-testnet-bug-bounty#35]
**Describe the bug**
1.注册节点显示名字被占用失败，但是仍然扣除掉了10个币。并且又因为注册节点手续费预留比例不够，显示insufficientbalance，再被扣除10个币。

2.设置链上身份时报如下错误 Custom error：255

**To Reproduce**
1.注册节点https://dapp-v2.chainx.org/#/staking
2.设置链上身份https://dapp-v2.chainx.org/#/accounts

**Expected behavior**
两种情况下交易均成功，且失败不用扣除10个币。

**Screenshots**
![图片](https://user-images.githubusercontent.com/74353104/99767781-8dafaf80-2b3e-11eb-8b92-7ecf6fd0790f.png)
![图片](https://user-images.githubusercontent.com/74353104/99767802-956f5400-2b3e-11eb-95de-1e8f4e1e4998.png)
![图片](https://user-images.githubusercontent.com/74353104/99767924-e717de80-2b3e-11eb-8fec-4c0043bc68c0.png)

**Account Info**
UserOrNode: SSSnodes
ChainX Wallet Address(Main Chain): 5HnRDTmZoaHQpy7yNbWWkVGdqLmMyNbhNo8U3rFVKUXMQcee

**Comment by liuchengxu** [comment]
`xStaking.OccupiedReferralIdentity` 是名字被占用，`setIdentity` 失败是因为目前只允许注册节点和参选，以及转账，其他交易尚未开放。
