### ISSUE TITLE
升级过程状态迁移不完全，节点30天的赎回冻结期抹除了

### ISSUE THREAD

**Issue by stw-github** [chainx-org/chainx-testnet-bug-bounty#36]
**Describe the bug**
升级过程状态迁移不完全，节点30天的冻结期自动抹除了。升级前节点赎回投票，升级后赎回的数量已经可转账，没有30天冻结期。

**Log**
参见交易：https://scan.chainx.org/txs/0xd119bb9db0927793e218e7c5004460faa6b2aaf4fdc24e3fe1c97c0a1ad8e662
11月18日撤销投票，升级后撤销的投票直接变为可转账，时间才过7天。
余额状态查询：https://scan-v2.chainx.org/accounts/5SWAPQw1XgFWvfgwZvLc4MHNiZQMJsrkNxgMcb3pxgRQmnbW

**Account Info**
UserOrNode: stw
ChainX Wallet Address(Major Chain): 5SWAPQw1XgFWvfgwZvLc4MHNiZQMJsrkNxgMcb3pxgRQmnbW

**Comment by liuchengxu** [comment]
这个情况我们考虑过，可接受。
