### ISSUE TITLE
Switching language doesn't apply to whole UI

### ISSUE THREAD

**Issue by shunjizhan** [chainx-org/chainx-testnet-bug-bounty#37]
**Describe the bug**
when switching language in `settings`, the top level navigation doesn't change language accordingly. 

**To Reproduce**
in 2.0 UI, switch language in `setting` from 汉语 to English, then click `save`

**Expected behavior**
Everywhere in UI should become English

**Log**
N/A

**Screenshots**
<img width="1680" alt="Screen Shot 2020-11-27 at 17 07 14" src="https://user-images.githubusercontent.com/16548786/100431752-8efb5200-30d3-11eb-9b83-ae54bbaa2ce2.png">

**Comment by alannotnerd** [comment]
Translation is in progress.
