### ISSUE TITLE
chainx2.0节点启动无法指定端口

### ISSUE THREAD

**Issue by stw-github** [chainx-org/chainx-testnet-bug-bounty#5]
**Describe the bug**
chainx2.0节点启动无法指定端口

**To Reproduce**
节点启动时通过“--rpc-port”指定端口

**Log**
error: The argument '--port ' was provided more than once, but cannot be used multiple times

**Account Info**
UserOrNode: stw
ChainX Wallet Address(Major Chain): 5SWAPQw1XgFWvfgwZvLc4MHNiZQMJsrkNxgMcb3pxgRQmnbW

**Comment by liuchengxu** [comment]
https://github.com/chainx-org/ChainX/pull/329 会进行修复

**Comment by koushiro** [comment]
Fixed by chainx-org/ChainX#329
