### ISSUE TITLE
浏览器数据显示与钱包数据显示不一致

### ISSUE THREAD

**Issue by wjdfx** [chainx-org/chainx-testnet-bug-bounty#8]
以地址：5H9HBrZCtMnWNKKcFbPKvwHSn6DFVoUHJexkQCbhS9GwZMHp 为例，他在浏览器里显示的数据是，很长时间没更新了：
自抵押40，总得票50
而在钱包里得票是，
自抵押40，总得票60
![image](https://user-images.githubusercontent.com/6984103/98262777-f7697e80-1fc0-11eb-96f5-51ee573c77ab.png)

节点： Bit Cat

**Comment by tarvos21** [comment]
Hi, @wjdfx , we have updated the validators list, how about it now? If no problem, please close the issue. Thanks!
